# http://about.travis-ci.org/docs/user/build-configuration/
language: python

python:
  - "2.6"

install:
  - python bootstrap.py 
  - bin/buildout

script: bin/sphinx-build -W -b html source build/html

notifications:
  email:
    - mikko@opensourcehacker.com
  irc: 
    channels: 
        - "irc.freenode.org#plone.org"
    on_success: never
    on_failure: change
