language: python

python:
  - "2.6"

install:
  - python bootstrap.py 
  - bin/buildout

script: bin/sphinx-build -W -b html source build/html

notifications:
  email:
    - mikko@opensourcehacker.com
    - other@example.com
  irc: "irc.freenode.org#plone.org"    