# http://about.travis-ci.org/docs/user/build-configuration/
language: python

python:
  - "2.6"

install:
  - python bootstrap.py
  - bin/buildout

script: bin/sphinx-build -b html source build/html

notifications:
  irc:
    channels:
        - "irc.freenode.org#plone-docs"
    on_success: never
    on_failure: change
